# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84a9efa1cf9a4461f4f7d878d910ff29476b1fa081c70a8136f0149d233610855f0ea64a185d756c252a524ee8dba752fa671e19105dc2e380989aab83ae8ee5

test:
  secret_key_base: f029f9a3ccae56e6b13c555420e173ef9dd3be524223328d1085b690a194dca7cba6668f9a68a9af2b433cc67e4749d52846312adc554352520dca6a2ba42626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
